import type { AppState } from "../domain/types";

function minutesFromNow(minutes: number): string {
  return new Date(Date.now() + minutes * 60_000).toISOString();
}

export function createInitialAppState(): AppState {
  const defaultUser = {
    id: "user-1",
    nickname: "김민수",
    email: "kimminsu@email.com",
    phone: "01012341234",
  };

  return {
    users: [defaultUser],
    session: {
      isAuthenticated: false,
      user: null,
    },
    auctions: [
      {
        id: "auction-1",
        title: "아이폰 15 Pro 256GB 블루티타늄",
        category: "전자기기",
        description:
          "구매 2개월, 사용감 거의 없는 상태입니다. 박스/케이블 구성품 포함, 애플케어 잔여.",
        images: [
          "https://images.unsplash.com/photo-1758186355698-bd0183fc75ed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
          "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
          "https://images.unsplash.com/photo-1592286927505-c2c7e4d443a3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
        ],
        condition: "거의새것",
        startPrice: 800000,
        currentBid: 950000,
        bidCount: 24,
        buyNowPrice: 1200000,
        endAt: minutesFromNow(45),
        createdAt: new Date().toISOString(),
        sellerId: "user-2",
        sellerName: "김민수",
        isSold: false,
        winnerUserId: null,
        highestBidderId: "user-3",
      },
      {
        id: "auction-2",
        title: "나이키 에어조던 1 레트로 하이",
        category: "패션",
        description: "정품, 박스 포함. 실착 3회.",
        images: [
          "https://images.unsplash.com/photo-1695459468644-717c8ae17eed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
        ],
        condition: "거의새것",
        startPrice: 120000,
        currentBid: 180000,
        bidCount: 18,
        buyNowPrice: 240000,
        endAt: minutesFromNow(120),
        createdAt: new Date().toISOString(),
        sellerId: "user-4",
        sellerName: "이서연",
        isSold: false,
        winnerUserId: null,
        highestBidderId: "user-5",
      },
      {
        id: "auction-3",
        title: "라이카 M6 필름카메라 (빈티지)",
        category: "수집품",
        description: "동작 상태 정상, 외관 A급.",
        images: [
          "https://images.unsplash.com/photo-1724627561609-9cd3facba8d4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
        ],
        condition: "사용감있음",
        startPrice: 1700000,
        currentBid: 2500000,
        bidCount: 12,
        buyNowPrice: 3200000,
        endAt: minutesFromNow(240),
        createdAt: new Date().toISOString(),
        sellerId: "user-6",
        sellerName: "박지훈",
        isSold: false,
        winnerUserId: null,
        highestBidderId: "user-1",
      },
      {
        id: "auction-4",
        title: "로렉스 서브마리너 시계",
        category: "수집품",
        description: "보증서 포함, 점검 완료.",
        images: [
          "https://images.unsplash.com/photo-1639564879163-a2a85682410e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
        ],
        condition: "거의새것",
        startPrice: 7200000,
        currentBid: 8500000,
        bidCount: 31,
        buyNowPrice: 9800000,
        endAt: minutesFromNow(30),
        createdAt: new Date().toISOString(),
        sellerId: "user-7",
        sellerName: "최도윤",
        isSold: false,
        winnerUserId: null,
        highestBidderId: "user-8",
      },
      {
        id: "auction-5",
        title: "샤넬 클래식 플랩백 미디엄",
        category: "패션",
        description: "백화점 구매 정품, 더스트백 포함.",
        images: [
          "https://images.unsplash.com/photo-1758171692659-024183c2c272?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
        ],
        condition: "거의새것",
        startPrice: 3000000,
        currentBid: 4200000,
        bidCount: 27,
        buyNowPrice: 5000000,
        endAt: minutesFromNow(180),
        createdAt: new Date().toISOString(),
        sellerId: "user-9",
        sellerName: "정유진",
        isSold: false,
        winnerUserId: null,
        highestBidderId: "user-4",
      },
      {
        id: "auction-6",
        title: "PS5 디지털 에디션 + 컨트롤러",
        category: "전자기기",
        description: "본체/컨트롤러 2개 포함.",
        images: [
          "https://images.unsplash.com/photo-1695028644151-1ec92bae9fb0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
        ],
        condition: "사용감있음",
        startPrice: 300000,
        currentBid: 420000,
        bidCount: 15,
        buyNowPrice: 550000,
        endAt: minutesFromNow(90),
        createdAt: new Date().toISOString(),
        sellerId: "user-10",
        sellerName: "한지민",
        isSold: false,
        winnerUserId: null,
        highestBidderId: "user-11",
      },
    ],
    bids: [
      {
        id: "bid-1",
        auctionId: "auction-1",
        bidderId: "user-3",
        bidderName: "김**",
        amount: 950000,
        createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
      },
      {
        id: "bid-2",
        auctionId: "auction-1",
        bidderId: "user-5",
        bidderName: "이**",
        amount: 920000,
        createdAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
      },
      {
        id: "bid-3",
        auctionId: "auction-1",
        bidderId: "user-7",
        bidderName: "박**",
        amount: 900000,
        createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      },
      {
        id: "bid-4",
        auctionId: "auction-1",
        bidderId: "user-8",
        bidderName: "최**",
        amount: 880000,
        createdAt: new Date(Date.now() - 32 * 60 * 1000).toISOString(),
      },
      {
        id: "bid-5",
        auctionId: "auction-1",
        bidderId: "user-12",
        bidderName: "정**",
        amount: 850000,
        createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
      },
    ],
    payments: [],
    counters: {
      auction: 7,
      bid: 6,
      payment: 1,
      user: 2,
    },
  };
}
